version: "3"

services:
  web:
    build:
      context: .
      args:
        - REQUIREMENTS=${REQUIREMENTS}
    command: gunicorn project.wsgi:application --timeout 300 --workers ${GUNICORN_WORKERS} --threads ${GUNICORN_THREADS} --bind 0.0.0.0:8000 --reload --access-logfile '-' --error-logfile '-'
    environment:
      URL: ${URL}
    volumes:
      - .:/code
      - apps_static_volume:/code/apps_static
      - ${LOCAL_MEDIA_VOLUME}${NAME}/public/uploads:/code/public/uploads
    expose:
      - 8000
    container_name: ${NAME}_web
  nginx:
    build: ./nginx
    ports:
      - "${PORT}:80"
    depends_on:
      - web
    volumes:
      - .:/code
      - apps_static_volume:/code/apps_static
      - ${LOCAL_MEDIA_VOLUME}${NAME}/public/uploads:/code/public/uploads
    links:
      - web:web
    container_name: ${NAME}_nginx

volumes:
  apps_static_volume:
